services:
  - type: web
    name: parakh-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --app-dir backend --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: postgresql://postgres.uexwdxeggghmkzapxfwn:Butter%40Chicken12@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres
      - key: GEMINI_API_KEY
        sync: false
